project_id = "awifqchcmsgjzzlvaizd"
[functions.send-otp-email]
enabled = true
verify_jwt = true
import_map = "./functions/send-otp-email/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send-otp-email/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send-otp-email/*.html" ]

[functions.send-otp-emai]
enabled = true
verify_jwt = true
import_map = "./functions/send-otp-emai/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send-otp-emai/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send-otp-emai/*.html" ]

[functions.sendgrid-mail]
enabled = true
verify_jwt = true
import_map = "./functions/sendgrid-mail/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/sendgrid-mail/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/sendgrid-mail/*.html" ]
